import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await readFile(new URL('../api/_engineer-max-delivery.js',import.meta.url),'utf8');
const shared=await readFile(new URL('../api/_shared.js',import.meta.url),'utf8');
const catalog=shared.match(/export const CATALOG=([\s\S]*?);\nexport function/)[1];
const imports='const getTbankPayment=()=>{},saveTbankPayment=()=>{},tbankCall=()=>{},safeTbankState=()=>{},verifyOrderToken=()=>false,ensureNpdReceiptForOrder=()=>{},engineerMaxFetch=()=>{},engineerMaxUpload=()=>{},get=()=>{},list=()=>{},put=()=>{},blobAuth=()=>{},starterProductHtml=()=>"offline-course";';
const stripped=source.replace(/^import .*;\n/gm,'');
const {deliverMaxOrder}=await import('data:text/javascript;base64,'+Buffer.from(imports+'const CATALOG='+catalog+';\n'+stripped).toString('base64'));
let order,sends,receipts,saves,status='paid';
const reset=()=>{order={product:'starter',paymentId:'123',maxUserId:100};sends=receipts=saves=0;status='paid';};
const deps={load:async()=>order,save:async(id,patch)=>{saves++;order={...order,...patch};return order;},state:async()=>({}),check:()=>({state:status}),verify:()=>true,receipt:async()=>{receipts++;},asset:async()=>({token:'fake-file'}),send:async(path,body)=>{assert.equal(path,'/messages?user_id=100');assert.equal(body.attachments[0].type,'file');assert.ok(!body.text.includes('vercel.app'));sends++;return{message:{body:{mid:'file-message'}}};}};
reset();await deliverMaxOrder('order',{},deps);assert.equal(sends,1);await deliverMaxOrder('order',{},deps);assert.equal(sends,1);
reset();status='pending';assert.equal((await deliverMaxOrder('order',{},deps)).state,'pending');assert.equal(sends,0);assert.equal(receipts,0);
reset();await assert.rejects(()=>deliverMaxOrder('order',{userId:101},deps),/owner_mismatch/);assert.equal(sends,0);
reset();delete order.maxUserId;await assert.rejects(()=>deliverMaxOrder('order',{userId:100}, {...deps,verify:()=>false}),/access_required/);assert.equal(saves,0);
reset();delete order.maxUserId;await deliverMaxOrder('order',{userId:100,productCode:'starter',accessToken:'valid'},deps);assert.equal(order.maxUserId,100);assert.equal(sends,1);
reset();await assert.rejects(()=>deliverMaxOrder('order',{}, {...deps,send:async()=>{throw new Error('failure');}}),/failure/);assert.ok(!order.maxDeliveredAt);
reset();status='failed';await deliverMaxOrder('order',{},deps);assert.equal(sends,0);
console.log('PASS: paid files, idempotent callback, pending/refund, owner isolation, signed legacy recovery, retry after failure');
